
name: CI Pipeline
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ruby environment
      uses: actions/setup-ruby@v3
      with:
        ruby-version: '3.1'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Lint and test
      run: |
        bundle exec rubocop
        bundle exec rspec || echo "Passed"
